### ISSUE TITLE
Support sendMediaGroup?

### ISSUE THREAD

**Issue by Gowee** [bytesnake/telebot#47]
Hi!

[sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) is a fantastic feature introduced in Bot API recently. In short, it allows sending multiple photos and video as an album (all those media are displayed as a single message like a jigsaw puzzle).

I look through roughly the implementation of the current version of *telebot*, finding it to be almost impossible to add this feature/function without heavily rewriting the file handling part of *telebot-derive*, which is beyond my ability.

Do you have any plans to support sendMediaGroup?

---
In case it helps, the following is my simplified implementation of this function for my own use. It only allows using URL or file id to send media, because it does not handle file upload at all. I have tested it and it works for me.
```rust
// in function.rs

/// Use this method to send a group of photos or videos as an album. On success, an array of the
/// sent Messages is returned.
#[derive(TelegramFunction, Serialize)]
#[call = "sendMediaGroup"]
#[answer = "Messages"]
#[function = "media_group"]
pub struct SendMediaGroup {
    chat_id: Integer,
    media: Vec<InputMedia>,
    #[serde(skip_serializing_if = "Option::is_none")]
    disable_notification: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    reply_to_message_id: Option<Integer>,
}


#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum InputMedia {
    // Animation,
    // Document,
    // Audio,
    Photo {
        #[serde(rename = "type")]
        type_: &'static str,
        /// URL or id.
        media: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        caption: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        parse_mode: Option<ParseMode>,
    },
    // Video,
}

impl InputMedia {
    pub fn photo(
        media: String,
        caption: Option<String>,
        parse_mode: Option<ParseMode>,
    ) -> InputMedia {
        InputMedia::Photo {
            type_: "photo",
            media: media,
            caption: caption,
            parse_mode: parse_mode,
        }
    }
}
```
```rust
// in objects.rs

pub type Messages = Vec<Message>; // To be compatible with telebot-derive.
```

**Comment by bytesnake** [comment]
Okay, I've heavily rewritten the file handling part and it should work now :smile: (commit fc5bdaff33ebeb13170b67dfa3bd4a3c9e4386ae)
I haven't introduced video galleries yet, because a logic to check the file ending is missing, but it should be relatively easy to add this later on.
You can find an example in `examples/send_mediagroup.rs`, if you're encountering any further problems please report. Otherwise just close the issue.

**Comment by Gowee** [comment]
Great! You are really productive. Thanks for the nice crate.

**Comment by Gowee** [comment]
Hi.

I still have a little question: it is `struct Message`, `struct MediaGroup`, but `struct SendPhoto`, `struct SendVideo`. Although those concrete functions are generated with the same prefix, would it be more consistent to take the same naming rule for these structs?

I am just a little curious about the reason. Feel free to ignore. :p

**Comment by bytesnake** [comment]
You we're just lucky that I got a free morning :smile: 
regarding your question, the struct name is irrelevant for the API, because telebot-derive gets the name from the function description above the struct. (e.g. "#[function = "photo"]") I think `SendMediaGroup` would be a better name though. (because it conveys the action of this function in a better way)

**Comment by bytesnake** [comment]
changed in e732b7f86ece72a1ba6d78b6427e8acf05ede7ac and 46c353633ddccf6720a5d251537b557aba0c7e8b

**Comment by Gowee** [comment]
Night for me. Good morning! :)
